import "./globals.css";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Routing Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={styles.nav}>
          <h1>Dealership</h1>
        </nav>
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
